### ISSUE TITLE
RAM machine: problem with loading programs

### ISSUE THREAD

**Issue by japro** [vbmacher/emuStudio#104]
Let's load (open and compile) a program into memory, e.g. reverse.ram from example programs. After we load (open and compile) a shorter program, e.g. copy.asm (also from the attached example programs in emuStudio), in the memory content, we can see that remainings of the longer program are still there (after HALT instr. at address 6). The picture shows how after the loaded _copy.asm_ program, still some garbage is there. 
![vyber_026](https://cloud.githubusercontent.com/assets/16756240/12873294/75a48db2-cdb9-11e5-9223-c8e1530cbe9e.png)

**Comment by japro** [comment]
Can I close this now?

**Comment by vbmacher** [comment]
Yes if it works
Dňa 13. 2. 2016 4:31 odpoludnia používateľ "japro" <notifications@github.com>
napísal:

**Comment by japro** [comment]
OK.
