### ISSUE TITLE
RAM module bugs

### ISSUE THREAD

**Issue by japro** [vbmacher/emuStudio#120]
- EmulatorEngine:getIntegerOperand() throws exception even if the operand is valid
- some instructions are interpreted incorrectly:

1.  after READ also WRITE is executed
2. JZ and JGTZ jump to incorrect addresses 

These bugs were probably introduced by mistake by this commit where some refactorings were performed: [https://github.com/vbmacher/emuStudio/commit/aeeffc30d6b41d898f1f9a44f2e1140e85be3983](url)

**Comment by vbmacher** [comment]
Thanks for solving it!
