### ISSUE TITLE
[ADM-3A] Software controlled cursor

### ISSUE THREAD

**Issue by MarcinWieczorek** [vbmacher/emuStudio#147]
Hello,
First of all, thank you for creating this software.
I've ran into an issue with ADM-3A and its load-cursor function.
I can see that it's implemented with the keyboard, the `ESC = Y X`, but it is also possible when sending that sequence to the port, at least in theory.
Here's the documentation I found: http://bitsavers.informatik.uni-stuttgart.de/www.computer.museum.uq.edu.au/pdf/DP-104%20ADM-3A%20Operators%20Manual.pdf
It would be also nice to have hardware switches implemented.

I wrote a hotfix, but I wanted to share, because I don't know a proper place to put this in.
```patch
diff --git a/plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/Display.java b/plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/Display.java
index 7a5ce0c9..ab551cc7 100644
--- a/plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/Display.java
+++ b/plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/Display.java
@@ -65,6 +65,9 @@ public class Display extends JPanel implements DeviceContext<Short>, TerminalSet
 
     private FileWriter outputWriter = null;
 
+    private int loadCursorActive = 0;
+    private int loadCursorY = -1;
+
     public Display(Cursor cursor, TerminalSettings settings) {
         this.settings = Objects.requireNonNull(settings);
         this.cursor = Objects.requireNonNull(cursor);
@@ -292,6 +295,28 @@ public class Display extends JPanel implements DeviceContext<Short>, TerminalSet
          * if it is special char, interpret it. else just add
          * to "video memory"
          */
+
+        // Implement load-cursor from code
+        switch (loadCursorActive) {
+            case 1:
+                if (data != '=') {
+                    loadCursorActive = 0;
+                }
+                else {
+                    loadCursorActive = 2;
+                }
+                return;
+            case 2:
+                loadCursorY = data - 32;
+                loadCursorActive = 3;
+                return;
+            case 3:
+                cursor.set(data - 32, loadCursorY);
+                loadCursorActive = 0;
+                repaint();
+                return;
+        }
+
         switch (data) {
             case 5: // HERE IS
                 insertString(HERE_IS_CONSTANT);
@@ -320,6 +345,7 @@ public class Display extends JPanel implements DeviceContext<Short>, TerminalSet
                 clearScreen();
                 return;
             case 0x1B: // initiates load cursor operation
+                loadCursorActive = 1;
             case 0x1E: // homes cursor
                 cursor.home();
                 break;

```

**Comment by vbmacher** [comment]
Hi @MarcinWieczorek ,  it's nice to see that emuStudio is used, thank you.

Regarding your question - I think you are right, ADM-3A should be able to recognize the "load cursor" function also from the serial port. I have actually found the code which should do it, but it's left unfinished (in `Display.write` method):

```java
...
            case 0x1B: // initiates load cursor operation
            case 0x1E: // homes cursor
...
```

I will not use your solution though. I think there should be just one place where the load-cursor sequence is checked, and which moves the cursor afterwards. I think the best would be to create a separate `LoadCursorPosition` class, which will be registered to `Keyboard` as device observer, and also given to `Display` which in fact also acts like serial I/O receiver (well... it's old code :) .

**Comment by MarcinWieczorek** [comment]
My code was a working hotfix, I can try to write a patch.

**Comment by vbmacher** [comment]
Ups, I was faster :( I have fixed it in 7583b84f12855b just now, sorry.. But I would be happy if you can check it. If it's still wrong, feel free to implement it better way. Thanks

**Comment by vbmacher** [comment]
And regarding the hardware switches you talked about, I don't have much time to implement them soon, but it is a good idea. We can discuss how you would imagine it and if you'd like to implement it.

**Comment by MarcinWieczorek** [comment]
I'm recompiling. That array you specified explicitly and now moved to LoadCursorPosition is ascii, that's where `data - 32` in my code came from. subtracting and checking boundaries is enough.

**Comment by MarcinWieczorek** [comment]
It doesn't work. It should get both X and Y coordinates, not just one of them.

**Comment by vbmacher** [comment]
Yes, I noticed this also. It should be fixed. It was implemented like this long time ago for the keyboard-style sequence, I just moved the original code to new place. 

Also, you are right about the array. I didn't notice the pattern there, just "rewrote" the table from the documentation.

Will you be fixing it, or should I?

**Comment by MarcinWieczorek** [comment]
I am at the very moment.

**Comment by vbmacher** [comment]
If you use `#147` in the commit message, the comment will be referenced in this issue. I failed this with the previous commit
