### ISSUE TITLE
Terminal on Mac OS X Doesn't work

### ISSUE THREAD

**Issue by Chipsi** [vbmacher/emuStudio#79]
Hello, I'm working on school project which need to use Terminal at Altair 8800 emu studio.
If I run my code, everything is compiled, bud when I click to show terminal, nothing will appear.

![screen shot 2015-03-09 at 09 37 53](https://cloud.githubusercontent.com/assets/862354/6551923/0a8a13b6-c640-11e4-91af-3542f5c72f00.png)

This mini window in Left Corner is my terminal... Any suggestions ?

**Comment by vbmacher** [comment]
Hello, I think you use some very old version of emuStudio :) Please try version 0.38b from here: http://emustudio.sourceforge.net/downloads.html. I never tried to run emuStudio on Mac OS X. If it won't work with new version, I can look at it.

**Comment by Chipsi** [comment]
Hello, I've tried example which print max_char_code from input, compiled it, and nothing changes.
![screen shot 2015-03-16 at 10 16 54](https://cloud.githubusercontent.com/assets/862354/6663303/a5a06168-cbc5-11e4-9b86-8da92e4f17b5.png)

Same result.

**Comment by vbmacher** [comment]
Hmm is it newest released version of emuStudio (0.38)? The terminal has been partially rewritten in development branch, you can also try to use not released version (0.39-SNAPSHOT). This would require recompiling emuStudio by yourself.

Unfortunatelly, I don't own any Mac and don't have access to the MacOS X environment. It would be great if you help me with the fix.

**Comment by Chipsi** [comment]
Yes, It is the lates version of emuStudio (0.38), I've downloaded it today from link you posted. Will try 0.39 branch.

**Comment by vbmacher** [comment]
I have decided not to officially support emuStudio on OS X for lack of time and resources. Closing the issue.
