### ISSUE TITLE
z80 JR xx,label incorrectly calculated offset

### ISSUE THREAD

**Issue by chriscamacho** [vbmacher/emuStudio#84]
Jump relative offsets are completely wrong - make the z80 basically unusable

**Comment by vbmacher** [comment]
You're right, currently the offset is not relative from the opcode start, but from the point after the opcode.. I will fix it in a minute.

**Comment by vbmacher** [comment]
Thank you very much for the issue. Can you please check if it is fine now?

**Comment by chriscamacho** [comment]
sorry but I really can't find anyway to help with this project the build system is just too needlessly complex

maven release target only seems do download compiled stuff from sf.net ?
maven compile target will compile stuff but I see no way to then run it ?
I'm unable to do any kind of code/compile/test cycle....

**Comment by vbmacher** [comment]
Yes, I agree. It is very complex in current days. I'm alone for the project so I must hold to priorities. Anyway, I am open to new ideas and willing to help.

Anyway, if you wasn't able to compile and run it, then it seems `README` file is not clear enough.

1. Compile the whole project with `mvn clean install` in the root dir
2. Go to `release` directory and compile it with `mvn install -P release`
3. In the `target` subdirectory you'll find ZIP and GZ files, both containing packed emuStudio dist.

Then you can unpack it wherever  you want and run it with `java -jar emuStudio`. That's it.

For increase development comfort, it is best to have Linux. Then I suggest to:

1. create subdirectories `compilers`, `config`, `mem`, `devices`, and `cpu` manually like in the distribution directory structure (`lib` is not necessary)
2. create symlinks of all targets of the plug-ins to particular directories (not very comfort way)
3. Run emuStudio main module (main class).

Then, whenever you make changes to any plug-in, and compile it, they will be reflected without any further intervention. If emuStudio is running, it then must be restarted.

**Comment by vbmacher** [comment]
I have created #87 for updating the README file about building and developing.

**Comment by chriscamacho** [comment]
try this:
    org     0000H
    ld      HL, message
loop:
    ld      A, (HL)
    cp      0
    jr      Z, end
    out     (11H), A
    inc     HL
    jp      loop

end:
    halt

message:
    db      "Hello world!",0
        
forward JR Z goes to wrong place (just cloned now)
also
change jp loop to jr loop - doesn't seem to do negative relative loops at all! :-o

the above still means I'm unzipping stuff every time I want to test a change?

**Comment by vbmacher** [comment]
Thanks for the testing sample. I will look at it.

You don't have to necessarily unzip all the time.. You just need to have prepared runtime environment - either in a separate directory (with complete emuStudio binary as in the ZIP), or as I suggested in Linux environment. Then the changed plug-in must be replaced in the correct place.

**Comment by chriscamacho** [comment]
Sorry not clear what you mean?
How *exactly* can I make a structure of directories and links to enable just compiled code either in main studio or plugin to run?
I'd be happy to make an ant build file with run/build/package targets if you can explain the structure of the project...

**Comment by chriscamacho** [comment]
don't forget to replace
jp loop
with
jr loop

negative relative jumps (conditional or not) are *very* important!

see page 167 of this http://www.phy.davidson.edu/FacHome/dmb/py310/Z80.Instruction%20set.pdf
bare in mind "e" can be negative!

**Comment by chriscamacho** [comment]
also page 242 has a negative jump and how to calculate it...

**Comment by vbmacher** [comment]
Thanks for the information; it is definitely helpful. I have created separate issue #85 for refactoring and fixing bugs in all the instructions. I will do it more globally, so similar situations should not happen.

Regarding directory structure, you can refer to user documentation in [user documentation](https://github.com/vbmacher/emuStudio/blob/branch-0_39/doc/src/userdoc/main_module/introduction.txt). For exact file mapping, unzip the relase ZIP file and look how it looks.. It is currently the only way.

**Comment by vbmacher** [comment]
Now I see problems only in my Z80 assembler. Now, `DJNZ`, `JR` as well as `JR cc` are broken to compile.

**Comment by vbmacher** [comment]
Now the problem should be fixed. I tried your example, and several others, including forward and backward jumps, and testing of boundaries (allowed are from -126 to 129). There were problems in both CPU (fixed earlier) and in assembler.

I will wait few days to double check from your side, after I will close the issue.

**Comment by chriscamacho** [comment]
I'm busy for now, please go ahead for now and close it, I'll look again and can always re-comment here or even open a new issue at a later date, hopefully I shouldn't need to!
