### ISSUE TITLE
RAM machine memory problem with loading

### ISSUE THREAD

**Issue by misomaevri** [vbmacher/emuStudio#93]
After loading a compiled program to program memory of RAM emulator, its disassembled form is not visible in the debug window, however, it is still possible to run and debug, but you do not see the instructions, it just steps through empty lines in debugger table.

**Comment by vbmacher** [comment]
It should work now. The problem was that:

1. you can open only compiled RAM program; error was not displayed if you tried to open source file. File extension in the open dialog was fixed to `*.ro` instead of `*.ram`.
2. changes were not propagated to the debug table
