### ISSUE TITLE
MITS Altair 8800, Intel 8080 emulator example programs problem

### ISSUE THREAD

**Issue by misomaevri** [vbmacher/emuStudio#94]
After compiling and starting all of the example programs included in the 'examples' folder, there is the same problem, that terminal does not react - it does not take any input.

**Comment by vbmacher** [comment]
The problem was that `ani` instruction was not compiled correctly.

Example program:

```Assembly
    jmp sample    ; C3 05 00
    ani 1         ; E6 01
sample:
    hlt           ; 76
```

was compiled into this sh*t:

```Assembly
    jmp 5         ; C3 05 00
    rst 0         ; C7
    lxi BC, 7600  ; 01 00 76    
```
