### ISSUE TITLE
Still sometimes problem with RAM machine memory

### ISSUE THREAD

**Issue by japro** [vbmacher/emuStudio#96]
In memory of RAM machine, the program loaded to memory from a file is still not displayed in the debug window. 

However, it sometime works, but only when debug window already holds some content, e.g. after some compilation.
 
So, to sum up, displaying of the program loaded to the memory from a file works only if the debug window already had some content.

**Comment by japro** [comment]
Well,  after long trying, finally the bug was that in this line 

https://github.com/vbmacher/emuStudio/blob/branch-0_39/plugins/mem/ram-mem/src/main/java/net/sf/emustudio/ram/memory/impl/RAMMemoryContextImpl.java#L139

only notifyMemoryChanged() is called. 

What was missing, was notification about memory size being changed, so adding this line:

notifyMemorySizeChanged();

after https://github.com/vbmacher/emuStudio/blob/branch-0_39/plugins/mem/ram-mem/src/main/java/net/sf/emustudio/ram/memory/impl/RAMMemoryContextImpl.java#L139 

fixes it.

**Comment by vbmacher** [comment]
So, please, fix it :) Do you know how to do it? If not, please read https://github.com/vbmacher/emuStudio/blob/branch-0_39/doc/src/tutorials/introduction.adoc

**Comment by japro** [comment]
It should be fixed now...

**Comment by vbmacher** [comment]
Dobry den,

je nejaky dovod preco ste zavreli ten PR (pull request)? Uz som sa tesil,
ze ako dobre ze to bude opravene, a vy ste to zatvorili :( Nevadi,
samozrejme, mam taky pocit, ze mozno potrebujete trosku pomoct/vysvetlit
ako to funguje?

Napisal som Vam komentar do commitu, stacilo ten commit upravit, ammendnut,
znova push-nut s parametrom --force, a hotovo. Ja viem, ze je to asi nieco
navyse, co od Vas skusam chciet, ale beriem to ako taky experiment s Vami,
ze aky ste sikovny :) A myslim ze Vam to zatial celkom ide, co ma tesi.

Tak skuste to nejak znova, ak by ste mali naozaj seriozny problem sa
pohnut, tak Vam pomozem.

Pekny vecer,

Peter J


2016-01-20 19:22 GMT+01:00 japro <notifications@github.com>:

**Comment by vbmacher** [comment]
This can be probably closed too now
